---

- name: prepare Raspberry Pi's
  hosts: all

  remote_user: ubuntu
  become: True
  become_user: root

  vars_files:
  - vars/main.yml

  pre_tasks:
  - name: upgrade the os
    ansible.builtin.apt:
      autoremove: True
      upgrade: dist

  roles:
  - role: ../../ansible-roles/micro-k8s

  tasks:
  - name: install temperature script
    ansible.builtin.copy:
      src: ../../scripts/temperature.py
      dest: /home/ubuntu/temperature.py
      owner: ubuntu
      group: ubuntu
      mode: '0744'
